CREATE TABLE IF NOT EXISTS `documents` (
    `id` VARCHAR(36) PRIMARY KEY,
    `company_id` VARCHAR(36) NOT NULL,
    `uploaded_by_user_id` VARCHAR(36) NOT NULL,
    `document_type` VARCHAR(100) NOT NULL,
    `file_name` VARCHAR(255) NOT NULL,
    `file_type` VARCHAR(100) NOT NULL,
    `file_size` BIGINT NOT NULL,
    `file_path` VARCHAR(2048) NOT NULL,
    `is_encrypted` BOOLEAN DEFAULT TRUE,
    `encryption_iv` VARCHAR(255) NULL,
    `checksum` VARCHAR(128) NULL,
    `status` ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    `expires_at` DATETIME NULL,
    `version` INT DEFAULT 1,
    `replaces_document_id` VARCHAR(36) NULL,
    `deleted_at` DATETIME NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY `idx_documents_company` (`company_id`),
    KEY `idx_documents_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_documents_company` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`),
    CONSTRAINT `fk_documents_uploader` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users`(`id`),
    CONSTRAINT `fk_documents_replaces` FOREIGN KEY (`replaces_document_id`) REFERENCES `documents`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
