CREATE TABLE IF NOT EXISTS `payments` (
    `id` VARCHAR(36) PRIMARY KEY,
    `company_id` VARCHAR(36) NOT NULL,
    `cohort_id` VARCHAR(36) NOT NULL,
    `invoice_id` VARCHAR(36) NOT NULL,
    `amount` DECIMAL(14, 2) NOT NULL,
    `currency` VARCHAR(3) DEFAULT 'IRR',
    `installment_number` INT DEFAULT 1,
    `method` ENUM('ZARINPAL', 'MANUAL_BANK_TRANSFER') NOT NULL,
    `status` ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED') DEFAULT 'PENDING',
    `payment_gateway` VARCHAR(255) NULL,
    `transaction_id` VARCHAR(255) UNIQUE NULL,
    `payment_intent_id` VARCHAR(255) UNIQUE NOT NULL,
    `bank_tracking_number` VARCHAR(255) NULL,
    `bank_transfer_date` DATETIME NULL,
    `manual_receipt_image_id` VARCHAR(36) NULL,
    `reviewed_by_id` VARCHAR(36) NULL,
    `reviewed_at` DATETIME NULL,
    `rejected_reason` TEXT NULL,
    `paid_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by_id` VARCHAR(36) NULL,
    KEY `idx_payments_company` (`company_id`),
    KEY `idx_payments_invoice` (`invoice_id`),
    CONSTRAINT `fk_payments_company` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`),
    CONSTRAINT `fk_payments_cohort` FOREIGN KEY (`cohort_id`) REFERENCES `cohorts`(`id`),
    CONSTRAINT `fk_payments_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`),
    CONSTRAINT `fk_payments_receipt_image` FOREIGN KEY (`manual_receipt_image_id`) REFERENCES `images`(`id`),
    CONSTRAINT `fk_payments_reviewer` FOREIGN KEY (`reviewed_by_id`) REFERENCES `users`(`id`),
    CONSTRAINT `fk_payments_creator` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
